version: 2

# CircleCI doesn't handle large file sets properly for local builds
# https://github.com/CircleCI-Public/circleci-cli/issues/281#issuecomment-472808051
localCheckout: &localCheckout
  run: |-
    PROJECT_PATH=$(cd ${CIRCLE_WORKING_DIRECTORY}; pwd)
    mkdir -p ${PROJECT_PATH}
    cd /tmp/_circleci_local_build_repo 
    git ls-files -z | xargs -0 -s 2090860 tar -c | tar -x -C ${PROJECT_PATH} 
    cp -a /tmp/_circleci_local_build_repo/.git ${PROJECT_PATH}

.openssh_job: &opensshjob
  docker:
    - image: ${IMAGE}
  steps:
    - checkout # change this from "checkout" to "*localCheckout" when running CircleCI locally
    - run:
        name: Set up SSH environment
        command: |
          mkdir -p -m 0755 /var/empty
          groupadd sshd
          useradd -g sshd -c 'sshd privsep' -d /var/empty -s /bin/false sshd
    - run:
        name: Clone liboqs
        command: cd oqs_test && scripts/clone_liboqs.sh
    - run:
        name: Build liboqs
        command: cd oqs_test && scripts/build_liboqs.sh
    - run:
        name: Build OpenSSH
        command: cd oqs_test && scripts/build_openssh.sh
    - run:
        name: Run unit tests
        command: cd oqs_test && python3 -m nose --rednose --verbose

jobs:
  # amd64-buster (Debian 10)
  ssh-amd64-buster-liboqs-master-with-openssl-with-pqauth:
    <<: *opensshjob
    environment:
      IMAGE: dstebila/liboqs:amd64-buster-0.0.2
      ARCH: x64
      WITH_OPENSSL: true
      WITH_PQAUTH: true
  ssh-amd64-buster-liboqs-master-with-openssl-no-pqauth:
    <<: *opensshjob
    environment:
      IMAGE: dstebila/liboqs:amd64-buster-0.0.2
      ARCH: x64
      WITH_OPENSSL: true
      WITH_PQAUTH: false
  ssh-amd64-buster-liboqs-master-no-openssl-no-pqauth:
    <<: *opensshjob
    environment:
      IMAGE: dstebila/liboqs:amd64-buster-0.0.2
      ARCH: x64
      WITH_OPENSSL: false
      WITH_PQAUTH: false
  # x86_64-xenial (Ubuntu 16.04)
  ssh-x86_64-xenial-liboqs-master-with-openssl-with-pqauth:
    <<: *opensshjob
    environment:
      IMAGE: dstebila/liboqs:x86_64-xenial-0.0.2
      ARCH: x64
      WITH_OPENSSL: true
      WITH_PQAUTH: true
  ssh-x86_64-xenial-liboqs-master-with-openssl-no-pqauth:
    <<: *opensshjob
    environment:
      IMAGE: dstebila/liboqs:x86_64-xenial-0.0.2
      ARCH: x64
      WITH_OPENSSL: true
      WITH_PQAUTH: false
  ssh-x86_64-xenial-liboqs-master-no-openssl-no-pqauth:
    <<: *opensshjob
    environment:
      IMAGE: dstebila/liboqs:x86_64-xenial-0.0.2
      ARCH: x64
      WITH_OPENSSL: false
      WITH_PQAUTH: false
      
workflows:
  version: 2
  build:
    jobs:
      - ssh-amd64-buster-liboqs-master-with-openssl-with-pqauth
      - ssh-amd64-buster-liboqs-master-with-openssl-no-pqauth
      - ssh-amd64-buster-liboqs-master-no-openssl-no-pqauth
      - ssh-x86_64-xenial-liboqs-master-with-openssl-with-pqauth
      - ssh-x86_64-xenial-liboqs-master-with-openssl-no-pqauth
      - ssh-x86_64-xenial-liboqs-master-no-openssl-no-pqauth
